sudo: required
services:
  - docker
language: python
cache: pip

env:
  - ORPC_TEST_VERSION="8.0" DOCKER_PG_IMAGE="postgres:9.4" TRAVIS_PYTHON_VERSION="2.7"
  - ORPC_TEST_VERSION="9.0" DOCKER_PG_IMAGE="postgres:9.4" TRAVIS_PYTHON_VERSION="2.7"
  - ORPC_TEST_VERSION="10.0" DOCKER_PG_IMAGE="postgres:9.4" TRAVIS_PYTHON_VERSION="2.7"
  - ORPC_TEST_VERSION="11.0" DOCKER_PG_IMAGE="postgres:9.4" TRAVIS_PYTHON_VERSION="2.7"
  - ORPC_TEST_VERSION="11.0" DOCKER_PG_IMAGE="postgres:9.4" TRAVIS_PYTHON_VERSION="3.7"
  # Tests on Odoo 12.0 are failing when loading of the generic chart of account
  #- ORPC_TEST_VERSION="12.0" DOCKER_PG_IMAGE="postgres:9.6" TRAVIS_PYTHON_VERSION="3.7"
  - ORPC_TEST_VERSION="13.0" DOCKER_PG_IMAGE="postgres:10" TRAVIS_PYTHON_VERSION="3.7"
  - ORPC_TEST_VERSION="14.0" DOCKER_PG_IMAGE="postgres:10" TRAVIS_PYTHON_VERSION="3.7"
  - ORPC_TEST_VERSION="15.0" DOCKER_PG_IMAGE="postgres:10" TRAVIS_PYTHON_VERSION="3.7"
  - ORPC_TEST_VERSION="16.0" DOCKER_PG_IMAGE="postgres:12" TRAVIS_PYTHON_VERSION="3.11"

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      script: echo "Deploy to PyPi"
      deploy:
        python: 3.11
        provider: pypi
        user: OCA
        password:
          secure: "FPirzG37lXBZIbMkE3EgTnOdU1ORRjKTRCwjyBtY2HZ0GIp0QCLk/KY6R0XWO+dKA2ZhF6aTV4BwheSoDITabDnEhiL6HKKku+QbJIBYk2TH2L5s2t1dr2330zJeOziAlHZ3usST415v1vESbAMxGhc20Yx/CUzenMi3sfQbua7wiwIzTiAJKQnFz6h0vGi2OezAi6Q4NxmnILJjXkeESGexLGldAcKr84NMwkm1+j/QQr/JuDZf/VSVSG7SAK++S2sA42pjph52mEDQrTxlqJ6QY1VXwokO8VI9NkULajcAUqYTHDD0pR2jchlk1EuoyB4Bn9h6Fc2xa3jcT/XnBrQc/QjNuv4MCH6DxWhVrMkcmI9bng2H3NqmkmSzsVmrLZSNiuS9lQKC2rcW2upL0+Dp+jA+xUYVPEQ64fAqkJq48Ef9aJfxIvQJA45v/XqVrh1X1J3eh/UqTvkwum4dIURU8KmaL+JUz1/ftz0uFkMDvvsygV55ybco3M6eN9CYwSIxGHs3zHeUjweVJcaoZv2Q7ZZ+OEoYiQ4ToyNrOkZl89f647NXHqgs4RuhyWcP3YxcW/iB87dNOtAkt0rGsbvYDMFzSpG/41VI7fYv+GT4km452BeTlX1tr1WT8zQQPSRsEsyqYD6AnWJQpLjKyPrDu3QV8CEYNmZjDHGCTiM="
        distributions: "sdist bdist_wheel"
        on:
          repo: OCA/odoorpc
          branch: master
          tags: true

before_install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ] ; then pip install -q pre-commit ; fi
  # Odoo instance
  - docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db $DOCKER_PG_IMAGE
  - docker run -d -p 8069:8069 --name odoo --link db:db -t "odoo:$ORPC_TEST_VERSION"

install:
  # OdooRPC dependencies
  - pip install sphinx

script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.7" ] ; then pre-commit run --all-files ; fi
  - python -m unittest discover -v
  - PYTHONPATH=.:$PYTHONPATH sphinx-build -b doctest -d doc/build/doctrees doc/source build/doctest
